/** Sector / theme tags for correlation limits */
export type Theme =
  | "AI"
  | "Semi"
  | "Energy"
  | "Finance"
  | "Consumer"
  | "Healthcare"
  | "ETF"
  | "Other";

export const THEME_LABELS: Record<Theme, string> = {
  AI: "AI / 软件",
  Semi: "半导体",
  Energy: "能源",
  Finance: "金融",
  Consumer: "消费",
  Healthcare: "医疗",
  ETF: "ETF",
  Other: "其他",
};

/** Map symbols to themes for sector correlation limits */
export const SYMBOL_THEMES: Record<string, Theme[]> = {
  AAPL: ["AI", "Consumer"],
  MSFT: ["AI"],
  NVDA: ["AI", "Semi"],
  TSLA: ["Consumer"],
  AMZN: ["Consumer", "AI"],
  META: ["AI"],
  GOOGL: ["AI"],
  AMD: ["AI", "Semi"],
  AVGO: ["Semi", "AI"],
  AMAT: ["Semi", "AI"],
  LRCX: ["Semi"],
  KLAC: ["Semi"],
  MU: ["Semi"],
  INTC: ["Semi"],
  TSM: ["Semi"],
  ASML: ["Semi"],
  SMCI: ["AI", "Semi"],
  ARM: ["Semi", "AI"],
  PLTR: ["AI"],
  CRM: ["AI"],
  ORCL: ["AI"],
  ADBE: ["AI"],
  NFLX: ["Consumer"],
  JPM: ["Finance"],
  BAC: ["Finance"],
  GS: ["Finance"],
  MS: ["Finance"],
  C: ["Finance"],
  WFC: ["Finance"],
  SCHW: ["Finance"],
  BLK: ["Finance"],
  IBKR: ["Finance"],
  COIN: ["Finance"],
  HOOD: ["Finance"],
  SOFI: ["Finance"],
  V: ["Finance"],
  MA: ["Finance"],
  PYPL: ["Finance"],
  SQ: ["Finance"],
  XOM: ["Energy"],
  CVX: ["Energy"],
  COP: ["Energy"],
  OXY: ["Energy"],
  SLB: ["Energy"],
  XLE: ["Energy", "ETF"],
  COST: ["Consumer"],
  WMT: ["Consumer"],
  HD: ["Consumer"],
  MCD: ["Consumer"],
  NKE: ["Consumer"],
  SBUX: ["Consumer"],
  DIS: ["Consumer"],
  F: ["Consumer"],
  GM: ["Consumer"],
  BABA: ["Consumer"],
  PDD: ["Consumer"],
  UBER: ["Consumer"],
  ABNB: ["Consumer"],
  UNH: ["Healthcare"],
  JNJ: ["Healthcare"],
  LLY: ["Healthcare"],
  ABBV: ["Healthcare"],
  MRK: ["Healthcare"],
  PFE: ["Healthcare"],
  MRNA: ["Healthcare"],
  SPY: ["ETF"],
  QQQ: ["ETF", "AI"],
  IWM: ["ETF"],
  XLF: ["Finance", "ETF"],
  XLK: ["AI", "ETF"],
  GLD: ["ETF"],
  SLV: ["ETF"],
  TLT: ["ETF"],
  HYG: ["Finance", "ETF"],
  CRWD: ["AI"],
  PANW: ["AI"],
  NET: ["AI"],
  SNOW: ["AI"],
  DDOG: ["AI"],
  ZS: ["AI"],
  SHOP: ["Consumer", "AI"],
  MSTR: ["Finance", "AI"],
  BA: ["Other"],
  CAT: ["Other"],
  GE: ["Other"],
  FCX: ["Energy"],
  NEM: ["Energy"],
};

export function getThemes(symbol: string): Theme[] {
  return SYMBOL_THEMES[symbol] || ["Other"];
}
